spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/my_mybatis_spring_boot_starter_demo;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;MODE=MYSQL;
    username: root
    password: root
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    initialization-mode: always
